[package]
name = "summera_tal"
version = "0.1.0"
authors = ["mikael <mikael.sahlestrom@topgolf.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
